### PR TITLE
[WIP] Fix relative paths

### PR DESCRIPTION
**Pull request by duboff**
With newer versions of Node, I get this error:

### CODE REVIEW

**Comment by vasilakisfil** [comment]
When trying to deploy to heroku I get this error:

```
remote:        BuildingBuilding.Building..Building...BuildingBuilding.Building..Build failed.
remote:        ENOENT: no such file or directory, scandir '/app/tmp/cache/node_modules/ember-highcharts/node_modules/'
remote:        Error: ENOENT: no such file or directory, scandir '/app/tmp/cache/node_modules/ember-highcharts/node_modules/'
remote:            at Error (native)
remote:            at Object.fs.readdirSync (fs.js:856:18)
remote:            at /app/tmp/cache/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:32:21
remote:            at Array.map (native)
remote:            at mergeRelativePath (/app/tmp/cache/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:30:29)
remote:            at /app/tmp/cache/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
remote:            at lib$rsvp$$internal$$tryCatch (/app/tmp/cache/node_modules/rsvp/dist/rsvp.js:493:16)
remote:            at lib$rsvp$$internal$$invokeCallback (/app/tmp/cache/node_modules/rsvp/dist/rsvp.js:505:17)
remote:            at lib$rsvp$$internal$$publish (/app/tmp/cache/node_modules/rsvp/dist/rsvp.js:476:11)
remote:            at lib$rsvp$asap$$flush (/app/tmp/cache/node_modules/rsvp/dist/rsvp.js:1198:9)
remote: 
remote:  !     Push rejected, failed to compile Ember CLI app
```

Is it related ?

**Comment by duboff** [comment]
It might be, but this problem only comes up on the new versions of Node. If you are on 0.12, everything should be working fine. I will try to finish this pr on the weekend, though it already works if you adjust the code manually.

**Comment by ahmadsoe** [comment]
@vasilakisfil  the problem is with npm version 3, on npm v3 all dependencies will be installed in app's `node_modules` folder with no nesting. You can downgrade to npm v2 or install this addon's dependencies manually until this pr finish.

```$ cd my-app/node_modules/ember-highcharts && npm install```

**Comment by duboff** [comment]
I have this problem with npm v2 as well on node v5.

**Comment by ahmadsoe** [comment]
I am on node v5 and npm v2 too. It's working perfectly fine.. did you get same error as @vasilakisfil ?

**Comment by joeczucha** [comment]
I've come up against somthing similar:

    version: 1.13.13
    Livereload server on http://localhost:49154
    Serving on http://localhost:4200/
    Attempting to watch missing directory: /Users/ian/Sites/mysite/mysite-ember/node_modules/ember-highcharts/node_modules
    Error: Attempting to watch missing directory: /Users/ian/Sites/mysite/mysite-ember/node_modules/ember-highcharts/node_modules
        at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/ian/Sites/mysite/mysite-ember/node_modules/broccoli-sane-watcher/index.js:90:11)
        at /Users/ian/Sites/mysite/mysite-ember/node_modules/broccoli/lib/builder.js:94:35
        at lib$rsvp$$internal$$tryCatch (/Users/ian/Sites/mysite/mysite-ember/node_modules/rsvp/dist/rsvp.js:493:16)
        at lib$rsvp$$internal$$invokeCallback (/Users/ian/Sites/mysite/mysite-ember/node_modules/rsvp/dist/rsvp.js:505:17)
        at /Users/ian/Sites/mysite/mysite-ember/node_modules/rsvp/dist/rsvp.js:1001:13
        at lib$rsvp$asap$$flush (/Users/ian/Sites/mysite/mysite-ember/node_modules/rsvp/dist/rsvp.js:1198:9)
        at doNTCallback0 (node.js:430:9)
        at process._tickCallback (node.js:359:13)

npm 3.3.12
node 5.1.0

ahmadsoe's workaround above solved it for me...

**Comment by duboff** [comment]
The workaround helps but you have to it every time you do npm cache clean and npm install which can be a pain. However, I am not sure why the CI is failing and had not been able to look into it. Everything works well locally with the proposed fix.

**Comment by joeczucha** [comment]
Cool, sounds good to me.

Not sure if this helps but I added `"ember-highcharts": "git@github.com:duboff/ember-highcharts.git",` to my package.json and run npm install. That finished fine, but then when I run ember serve I get the following:

    version: 1.13.13
    Cannot find module 'highstocks-release/highstocks.js'
    Error: Cannot find module 'highstocks-release/highstocks.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.require.resolve (module.js:389:19)
        at Class.module.exports.treeForVendor (/Users/joe/Sites/myapp-ember/node_modules/ember-highcharts/index.js:13:66)
        at Class._treeFor (/Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/models/addon.js:319:31)
        at Class.treeFor (/Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/models/addon.js:289:19)
        at /Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:369:20
        at Array.map (native)
        at EmberApp.addonTreesFor (/Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:367:30)
        at EmberApp._processedVendorTree (/Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:796:29)
        at EmberApp._processedExternalTree (/Users/joe/Sites/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:826:21)

Could that have anything to do with it? It might be something completely different :)

**Comment by ahmadsoe** [comment]
> Since Highcharts now using single bower package for all modules, this addon now imports highcharts source from bower_components.

**Pull request closed without merging**
