### PR TITLE
Add support for updating chart when series data is removed

### PR DESCRIPTION
**Pull request by gregjopa**
This PR fixes issue #47. It also includes a component-based redesign of the dummy app. The dummy app now includes an "interactive chart" widget that can be used to test removing chart series data.

### CODE REVIEW

**Comment by gregjopa** [comment]
@ahmadsoe - please review

**Comment by ahmadsoe** [comment]
@gregjopa Can you add some tests? Otherwise, this looks pretty great to me.

**Comment by gregjopa** [comment]
Good point. I added a couple integration tests for this.

**Comment by ahmadsoe** [comment]
Perfect. Thanks!

**Pull request merged**
