### PR TITLE
[FEATURE add-highcharts-more] Add includeHighChartsMore config option.

### PR DESCRIPTION
**Pull request by malchak**
This PR is in regards to the feature request [issue #25 ](https://github.com/ahmadsoe/ember-highcharts/issues/25) submitted by @gregjopa.  Included are updates to the index.js and README.md files, as well as the addition of the hightcharts-more-release folder and corresponding source file to the vendor directory.

### CODE REVIEW

**Comment by gregjopa** [comment]
:+1:  I tested this locally in my project and verified that it works. Nice work @malchak !

**Comment by ahmadsoe** [comment]
Thanks.

**Comment by gregjopa** [comment]
@ahmadsoe can you please publish a new version of this addon to npm? I'd like to use this new feature.

**Comment by ahmadsoe** [comment]
@gregjopa I've just publish a new version 0.1.3

**Comment by gregjopa** [comment]
@ahmadsoe thanks :smile:

**Pull request merged**
