### PR TITLE
Support HighCharts 'styled' mode - separating styling concerns using CSS - applicable since version 5

### PR DESCRIPTION
**Pull request by edslocombe**
Added some very basic support to allow use of the [Styled mode](http://www.highcharts.com/docs/chart-design-and-style/style-by-css) core HighCharts library.

### CODE REVIEW

**Comment by gregjopa** [comment]
I did some review of using this addon with Highcharts version 5.02 and there are two problems:

1. The "should update data on all svg paths on highstock chart" integration test fails. Error message: "Attempted to assign to readonly property"
2. The funnel chart example in dummy/app is throwing an error. It fails mid render with the error message "Cannot read property 'breakArray' of undefined". Our funnel is nearly identical to this fiddle which works fine with HighCharts v5: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/funnel/. 

According to the change log there are no breaking changes for HighCharts 5: http://www.highcharts.com/documentation/changelog. I haven't had any luck debugging this. Any help with troubleshooting these two issues with HighCharts 5 would be appreciated.

I'd like to pause on adding any docs about v5 until these issues are resolved.

**Comment by nickmagnabosco** [comment]
It's now in synch with master. @gregjopa all tests are passing and the example works fine.

**Comment by gregjopa** [comment]
This PR seems fine to me. I'm no longer using ember or ember-highcharts so I'm no longer contributing to this project. @ahmadsoe, can you review this?

**Comment by ahmadsoe** [comment]
@gregjopa Sure. Thank you for all your efforts on this project.

@nickmagnabosco can you rebase this against master, before I start the review?

**Comment by nickmagnabosco** [comment]
@ahmadsoe done

**Comment by ahmadsoe** [comment]
After some review, I decided to merge PR #124 instead of this.

@nickmagnabosco thanks for contributing.

**Pull request closed without merging**
