### PR TITLE
Make chart options updatable by calling drawAfterRender in didReceive…

### PR DESCRIPTION
**Pull request by broldak**
…Attrs

Currently high-charts' draw() method is only called on didInsertElement. This means that if any options change without the chart being re-inserted, they won't be picked up by didReceiveAttrs' chart.redraw() call. This PR adds a call to drawAfterRender() in didReceiveAttrs so that options can be updated without the component being re-rendered.

### CODE REVIEW

**Comment by broldak** [comment]
Added tests to confirm that chart title can be updated. All tests passing.

**Comment by nlfurniss** [comment]
Can you rebase to pull in the latest changes? Should fix the travis test failure

**Comment by broldak** [comment]
@nlfurniss rebased.

**Comment by broldak** [comment]
@nlfurniss Any thoughts on this change?

**Comment by cs3b** [comment]
can be closed in favor of #159

**Pull request closed without merging**
