### PR TITLE
Clean up tests

### PR DESCRIPTION
**Pull request by gregjopa**
This PR makes some minor improvements to the test suite. The StockChart test has been converted over to an integration test. Based on this documentation it seems like we should be writing integration tests for components instead of unit tests: https://github.com/rwjblue/ember-qunit#component-integration-tests. However, I ran into a problem converting the "credits" unit tests over to integration tests. I couldn't find a way to properly stub and clear the highcharts-config in an integration test (I tried using `this.register()` but didn't have any luck). So I left these as unit tests.

The 'has default options' unit test was misleading because it didn't actually validate the default options were being set. The `highcharts-configs` from the tests/dummy/app gets loaded right away in the unit tests. So the credits text is "'ember-highcharts-configured-title'" in all of the unit tests. Due to this behavior I moved the assertion from 'has default options' into the 'has local options' test. So now there is a single unit test for validating the credits text.

### CODE REVIEW

**Comment by ahmadsoe** [comment]
@gregjopa I just pull this pr and try to move the 'has local options' test to integration test, it seems to work and the test passed. look likes that integration test had already picked up the `highchart-config` on dummy app.

**Comment by gregjopa** [comment]
@ahmadsoe thats a good point. I updated the "local options" test to be an integration test. All the tests passed. I added a comment to describe how the `highcharts-config` is auto-loaded in the integration test.

Do you think we should keep the unit test file? Right now, there is only one test in it for component state using `this.subject()._state` which isn't mentioned in the Ember testing docs. I think we should delete this unit testing file and just focus on integration tests.

**Comment by ahmadsoe** [comment]
Yes, I think it's fine to remove those unit testing.

**Comment by gregjopa** [comment]
@ahmadsoe sounds good. I deleted the unit test file.

**Comment by ahmadsoe** [comment]
@gregjopa thank you.

**Pull request merged**
